<?php
/**
 * Utility class I use to generate the code needed for configuration pages.
 * User: blake
 * Date: 9/3/12
 * Time: 8:56 PM
 *
 * Instructions:
 * 1) edit the asterisk_config_meta.php
 * 2) Run script. (php configuratorGeneratorUtil.php > asterisk_configurator_table.tpl)
 * 3) Look at the asterisk_configurator_table.tpl if any mod_strings aren't defined they'll be listed there.
 */
define('sugarEntry', true);
define('configurator_util', true);
@require_once 'language/en_us.lang.php';
@require_once 'asterisk_config_meta.php';
global $config_meta;
global $mod_strings;

print "<!-- THIS FILE IS AUTOGENERATED BY RUNNING configuratorGeneratorUtil > asterisk_configurator_table.tpl -->";
sleep(3);

/*
$$config_meta['asterisk_host'] 	= array('default' => '127.0.0.1', 'section'=>'Asterisk Server Settings');
$config_meta['asterisk_port'] 	= array('default' => '5038', 'type'=>'int', 'section'=>'Asterisk Server Settings');
$config_meta['asterisk_user'] = array('default' => 'ami_user', 'section'=>'Asterisk Server Settings');
$config_meta['asterisk_secret'] = array('default' => 'ami_pass', 'section'=>'Asterisk Server Settings');

$config_meta['asterisk_soapuser'] = array('default' => 'admin','section'=>'SugarCRM SOAP Settings' );
$config_meta['asterisk_soappass'] = array('default' => 'soap_password','section'=>'SugarCRM SOAP Settings');

$config_meta['asterisk_prefix'] = array('default' => '', 'section'=>'Call Configuration', 'required'=>'FALSE');
$config_meta['asterisk_dialinPrefix'] = array('default' => '','section'=>'Call Configuration', 'required'=>'FALSE');
$config_meta['asterisk_context'] = array('default' => 'from-internal','section'=>'Call Configuration');
$config_meta['asterisk_expr'] = array('default' => '^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)','section'=>'Call Configuration');
$config_meta['asterisk_dialout_channel'] = array('default' => 'SIP/###','section'=>'Call Configuration');
$config_meta['asterisk_dialin_ext_match'] = array('default' => 'Local\/(?:.*?)(\d\d\d?\d?\d?)@','section'=>'Call Configuration');
$config_meta['asterisk_rg_detect_expr'] = array('default'=>"^Local\/RG",'section'=>'Call Configuration');
$config_meta['asterisk_rg_cell_ring_expr'] = array('default'=>"^Local\/\d{7,10}",'section'=>'Call Configuration');
$config_meta['asterisk_digits_to_match'] = array('default' => '8', 'section'=>'Call Configuration');

$config_meta['asterisk_call_subject_inbound_abbr'] = array('default' => "IBC: ", 'section'=>'Misc');
$config_meta['asterisk_call_subject_outbound_abbr'] = array('default' => "OBC: ",'section'=>'Misc');
$config_meta['asterisk_call_subject_max_length'] = array('default' => '50','section'=>'Misc');
$config_meta['asterisk_listener_poll_rate'] = array('default' => '5000','section'=>'Misc');
$config_meta['asterisk_opencnam_enabled'] = array('default' => 'false','section'=>'Misc');
$config_meta['asterisk_opencnam_username'] = array('default'=> '', 'section' => 'Misc');
$config_meta['asterisk_opencnam_apikey'] = array('default' => '', 'section'=>'Misc');
$config_meta['asterisk_opencnam_retries'] = array('default'=> '4', 'section'=>'Misc');
$config_meta['asterisk_gravatar_enabled'] = array('default' => 'false','section'=>'Misc') ;
$config_meta['asterisk_short_call_status'] = array('default' => "Held",'section'=>'Misc');
$config_meta['asterisk_hide_call_popups_after_mins'] = array('default' => '60','section'=>'Misc');

$config_meta['asterisk_log_file'] = array('default' => '', 'section'=>'Logging');

$config_meta['asterisk_fop_url'] = array('default' => '', 'section'=>'Flash Operator Panel Addon');
$config_meta['asterisk_fop_master_password'] = array('default' => '', 'section'=>'Flash Operator Panel Addon');

$config_meta['asterisk_block_button_enabled'] = array('default' => 'false', 'section'=>'Popup UI');
$config_meta['asterisk_fop_button_enabled'] = array('default' => 'false', 'section'=>'Popup UI');
$config_meta['asterisk_transfer_button_enabled'] = array('default' => 'true', 'section'=>'Popup UI');
$config_meta['asterisk_relate_to_account_enabled'] = array('default' => 'true', 'section'=>'Popup UI');
$config_meta['asterisk_relate_to_contact_enabled'] = array('default' => 'true', 'section'=>'Popup UI');
$config_meta['asterisk_create_new_contact_enabled'] = array('default' => 'true', 'section'=>'Popup UI');
$config_meta['asterisk_max_popups'] = array('default' => '5', 'section'=>'Popup UI');
$config_meta['asterisk_filtered_call_states'] = array('default' => '', 'section'=>'Popup UI');
$config_meta['asterisk_window_height'] = array('default' => '', 'section'=>'Popup UI');


$config_meta['asterisk_callinize_organization_key'] = array('default' => '', 'section'=>'Callinize');
$config_meta['asterisk_callinize_organization_secret'] = array('default' => '', 'section'=>'Callinize');


//$config_meta['asterisk_recordings_enabled'] = array('default'=> 'false', 'section'=>'Recordings');
//$config_meta['asterisk_recordings_path'] = array('default' => '/var/spool/asterisk/monitor', 'section'=>'Recordings');
*/


$columnSmarty=<<<'END'
    <td nowrap width="10%" class="dataLabel">{$MOD.LBL_@@UPPER@@}
      {if !empty($MOD.LBL_@@UPPER@@_DESC)}
          [<a href="#" title="{$MOD.LBL_@@UPPER@@_DESC}">?</a>]:
      {/if}
    </td>
    <td width="25%" class="dataField">
    {if empty($config.@@NORMAL@@ )}
        {assign var='@@NORMAL@@' value=$asterisk_config.@@NORMAL@@}
    {else}
        {assign var='@@NORMAL@@' value=$config.@@NORMAL@@}
    {/if}
        <input type='@@TYPE@@' name='@@NORMAL@@' size="45" value='{$@@NORMAL@@}'>
    </td>
END;

$i = 0;
$prevSection='';
    foreach ($config_meta as $key => $value) {
    $in = $columnSmarty ;

    // Once section changes we insert a new header
    if( $value['section'] != $prevSection ) {
        $prevSection = $value['section'];
        if( $i%2 == 1 ) {
            print "<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>";
            $i++;
        }
        print "\n\n<TR><td colspan=\"4\">&nbsp;&nbsp;<TR><TD colspan=\"4\"><h3>{$value['section']}</h3></TD></tr>\n";
        $sectionHdr = "LBL_ASTERISK_SECTIONHDR_" . strtoupper($value['section']);
        if( array_key_exists($sectionHdr, $mod_strings) ) {
            print "<TR><TD colspan=\"4\">{$mod_strings[$sectionHdr]}</TD></tr>";
        }
    }

    if( ($i % 2) == 0)
        print "\n\n<TR>\n\n";

    $type = "textbox";
    if( isset($value['type'] ) ) {
        if( $value['type'] == "bool") {
            $type = "checkbox"; // checkbox is too hard to support since it's value isn't submitted when form is posted and it's unchecked!
        }
        else {
            $type = $value['type'];
        }
    }

    $out  = str_replace(
        array('@@UPPER@@','@@NORMAL@@','@@TYPE@@'),
        array(strtoupper($key),$key,$type),
        $in);

    print $out . "\n\n";

    $i++;
}

if( $i%2 == 1 ) {
    print "<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>";
}

//print "\n\n\n -- FOR SugarModules/Configurator/language/en_us.lang.php ------\n\n";

$missingCnt = 0;
foreach ($config_meta as $key => $value) {
    $msKey = "LBL_" . strtoupper($key);
    if( !array_key_exists($msKey, $mod_strings) ) {
        print "$" . "mod_strings['" . "LBL_" . strtoupper($key) . "'] = 'TODO DEFINE';" . "\n";
        $missingCnt++;
    }
}
if( $missingCnt == 0 ) {
    //print "Congrats, all required modstrings for field labels are defined!\n";
}
else {
    print "WARNING: don't forget to define the modstrings above!\n\n";
}








